### ISSUE TITLE
Temperature Chamber Example Uses Bad UDP IP Address, Should be 'Localhost'

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/DCAF-Examples#13]
It'd be better if this was something people didn't have to change.

**Comment by becega** [comment]
IF they move from one target to the other it will change we can update the logic but that will be after niweek

**Comment by Beazurt** [comment]
True, but I think it'd be best to make the default 'localhost' so that users can run both engines on windows without modification.

**Comment by Beazurt** [comment]
Fixed in 544171f
