### ISSUE TITLE
Update Documentation to handle running both engines on the host

### ISSUE THREAD

**Issue by cloew-ni** [LabVIEW-DCAF/DCAF-Examples#16]
See discussion https://decibel.ni.com/content/message/142164

Q: When I try to run Host Main.vi in the Temperature Controller Example, I get a pop up stating that an error occurred at Loadclass.vi because it could not find the Temperature Controller Logic configuration.lvclass. I'm assuming it wouldn't find the other classes either if it was allowed to continue. Do I need to manually add the classes to the project? Thanks

A: If you have both engines under the PC target in your configuration, you'll need to make sure you've rescripted the host includes file to reflect that.  In the DCAF Configuration Editor, go to Tools and choose the option to rescript the includes VI for the PC target.  After doing this it should work for you.  You do not need to manually add classes to the project - this is what the includes VI takes care of for you.

**Comment by brbrindle** [comment]
Might also be good to add the following.

Script include only needs run when engines are created/moved and when modules are added.

Other wise configuration file holds all other information.

**Comment by Beazurt** [comment]
All modules have been added to the Host Includes VI in the shipping example.
