### ISSUE TITLE
PID Function Doesn't Ship With Standard LV

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/DCAF-Examples#2]
The PID function currently used by the sample application is not something all users have access to.  We should replace this with a community-sourced PID function.

**Comment by smithed** [comment]
Most users should have access to it. The placeholder used in the R&D sample projects made sense, it doesn't matter as much here. Not saying its not a good idea, just not high priority.

**Comment by Beazurt** [comment]
yeah, I know of a good one that I can use.  Should just take a second for me to fix it.  Last time I had someone try it they didn't have access so the example opened broken (which wasn't a good first impression).

**Comment by smithed** [comment]
yes but was it a customer? we tend to package the controls stuff in with rt/fpga, so many customers will install it automatically. 

anyway, make sure you check licensing on the PID.
