### ISSUE TITLE
Example does not have System Configuration in includes

### ISSUE THREAD

**Issue by theSloopJohnB** [LabVIEW-DCAF/DCAF-Examples#21]
Running the example produces the following error:

![image](https://user-images.githubusercontent.com/26978265/30830000-1a6d1048-a208-11e7-9ae2-129088056077.png)

Explain Error

![system diagnostics error](https://user-images.githubusercontent.com/26978265/30828497-763f822a-a203-11e7-9a2f-21a23edc20dd.PNG)

This seems to be because the example does not have module runtimes in the includes script:

![includesbd](https://user-images.githubusercontent.com/26978265/30828627-df844dd8-a203-11e7-8fec-6d7bccfec09c.PNG)

Compare the script to the configuration file:

![image](https://user-images.githubusercontent.com/26978265/30830066-4d7d185c-a208-11e7-96a6-8013f96924c5.png)

Missing from the script are System Diagnostics, Scan Engine, and watchdog configuration.

I will attempt to fix on my test setup and report back.

This error does not prevent the example from running, it just means that the values coming out of some tags are 0.

**Comment by theSloopJohnB** [comment]
Adding the missing runtime classes to the includes script results in lots of of scary deployment errors:

    LabVIEW:  Failed to load shared library niwd4c.*:maketNIWatchdogActionParamTrigger:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:iNIWatchdog_addAction:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:observeOccurrence:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:iNIWatchdog_addAction:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:maketNIWatchdogActionParamReset:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:iNIWatchdog_addAction:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:iNIWatchdog_set:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:iNIWatchdog_reset:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:tNIWatchdogFactory_reserve_noCleanupProc:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:tNIWatchdogFactory_reserve:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:tNIWatchdogFactory_relinquish:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:iNIWatchdog_configure:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:iNIWatchdog_enable:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.
    LabVIEW:  Failed to load shared library niwd4c.*:iNIWatchdog_whack:C	. Ensure that the library is present on the RT target. Use either MAX to install NI software or FTP to transfer custom libraries to the RT target.Watchdog Add Interrupt Action.vi loaded with errors on the target and was closed.

It seems like I need to install some additional things to my target.

As this is outside of the normal workflow for example users, I don't want to poke around on it too much more. It does seem weird to me to have the example in this state that doesn't 'just work.' There's also no mention in the PDF guides about needing to deploy additional things from the watchdog.

**Comment by theSloopJohnB** [comment]
To fix this, update documentation for all instructions to get working, e.g. the watchdog deployment from MAX.

**Comment by dbendele** [comment]
The Temperature Chamber Quick Start Guide is scoped to the Simulated System configuration. The Temperature Chamber Detailed Documentation examines the implementation, but assumes "you likely don't have the hardware dependencies necessary to actually run the example."

**Comment by dbendele** [comment]
fixed by commit:
https://github.com/LabVIEW-DCAF/DCAF-Examples/commit/6e9a1be5fb62487a383d4338b4bb22c2a640f4d9
