### ISSUE TITLE
Error during includes file scripting: File Dialog2, File version is later than the current LabVIEW Version

### ISSUE THREAD

**Issue by theSloopJohnB** [LabVIEW-DCAF/DCAF-Examples#22]
While running the script includes VI on the example, I ran into this error:

![image](https://user-images.githubusercontent.com/26978265/30828874-b588d8c2-a204-11e7-8d10-d407d2d55cd4.png)

LabVIEW version I tested:

![image](https://user-images.githubusercontent.com/26978265/30828938-f4b10574-a204-11e7-913f-73dad8ebf133.png)
2014, SP1. Version 14.0.1, 32 bit.

People shouldn't have to do this on the example. I will try running this on some other things as well.

**Comment by theSloopJohnB** [comment]
Investigate cross linking issue.

**Comment by theSloopJohnB** [comment]
I tried doing this again and I was not able to reproduce it.

**Comment by dbendele** [comment]
not reproducible.
