### ISSUE TITLE
There is missing "SCAN Engine" when open DCAF example by labview2017 64bit

### ISSUE THREAD

**Issue by Daniel-weng** [LabVIEW-DCAF/DCAF-Examples#28]
My labview was 2017 64bit. when i download DCAF core in VIPM and all the installment was finished. When i open the DCAF example "Temp controller Example" . The "NI SCAN Engine"can not be found. is there any way that i could download the NI SCAN Engine separately that i could select this folder manually.

**Comment by becega** [comment]
As mentioned on the forum : [NI SCAN ENGINE" files missing in the DCAF example ](https://forums.ni.com/t5/Distributed-Control-Automation/quot-NI-SCAN-ENGINE-quot-files-missing-in-the-DCAF-example/gpm-p/3780149#M399)
Scan engine is part of LabVIEW Realtime and it is only supported on 32 bits. 
You can run the simulated example without scan engine.
