### ISSUE TITLE
gains don't seem to be appropriate for sim mode @100ms

### ISSUE THREAD

**Issue by smithed** [LabVIEW-DCAF/DCAF-Examples#3]
defaults are 15,.1,.1. This seems to have significant overshoot and settle over 30 C (vs 25 C setpt). Setting so about 15, 0.01, 0 seems to work better.

**Comment by Beazurt** [comment]
Yep.  Somehow the default values were lost during one of the updates to 2.0 so I just guessed at what they were.  Your values seem like they would work better.

**Comment by smithed** [comment]
bump @Beazurt

**Comment by Beazurt** [comment]
Tuning may not be ideal, but it doesn't settle at the wrong setpt anymore. I ended up using 15, .1, and .003.
